version: '3'
services:
  go:
    depends_on:
      - db
    build: server
    restart: always
    ports:
      - "5000:5000"
    environment:
      MYSQL_DATABASE: 'go'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_HOST: db
      MYSQL_PORT: 3306
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'go'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'root_password'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - godb:/var/lib/mysql
volumes:
  godb:
